version: '3'

services:
  server:
    image: "service"
    ports:
      - 5001:5001
    depends_on:
      - db

  client:
    image: "client"
    ports:
      - 3000:3000
    depends_on:
      - server

  db:
    image: "db"
    ports:
      - 27017:27017
