version: '3'

services:
  server:
    image: "koushrk/toptrumps-server"
    ports:
      - 5001:5001
    depends_on:
      - db

  client:
    image: "koushrk/toptrumps-client"
    ports:
      - 3000:3000
    depends_on:
      - server

  db:
    image: "koushrk/toptrumps-db"
    ports:
      - 27017:27017
