name: Docker Publish

on:
  push:
    # Publish `develop` as Docker `latest` image.
    branches:
      - develop

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: toptrumps-client

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}

      - name: Tags
        run: |
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USER }}/$IMAGE_NAME:$(date +%s)
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USER }}/$IMAGE_NAME:latest

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/$IMAGE_NAME:$(date +%s)
          docker push ${{ secrets.DOCKER_USER }}/$IMAGE_NAME:latest
